backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "start"
    label: "start"
    folder: "content/start/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "start"
    fields:
      - label: "snabb info 1"
        name: "snabb_info_one"
        widget: "markdown"
        required: false
      - label: "snabb info 2"
        name: "snabb_info_two"
        widget: "markdown"
        required: false
      - label: "info"
        name: "info"
        widget: "markdown"
        required: false
      - label: "sale info"
        name: "sale"
        widget: "markdown"
        required: false
      - label: "Bra att veta 1"
        name: "good_to_know_one"
        widget: "markdown"
        required: false
      - label: "Bra att veta 2"
        name: "good_to_know_two"
        widget: "markdown"
        required: false
      - label: "Bra att veta 3"
        name: "good_to_know_three"
        widget: "markdown"
        required: false

  - name: "konserter"
    label: "Konserter"
    folder: "content/konserter/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "konserter"
    fields:
      - label: "Innan"
        name: "innan"
        widget: "string"
        required: false
      - name: konserter
        label: Konserter
        label_singular: "Konsert"
        widget: list
        summary: "{{fields.artist}}"
        fields:
          - label: "Text innan specifik konsert"
            name: "Text_before_specific_concert"
            widget: "string"
            required: false
          - label: "Artist"
            name: "artist"
            widget: "string"
            hint: "Namn på artist/grupp"
          - label: "Datum"
            name: "datum"
            widget: "datetime"
            format: "YYYY-MM-DD"
            dateFormat: "YYYY-MM-DD"
            timeFormat: false
            hint: "Datum för spelning"
      - label: "Efter"
        name: "efter"
        widget: "string"
        required: false

  - name: "klassiska-konserter"
    label: "Klassiska konserter"
    folder: "content/klassiska-konserter/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "klassiska konserter"
    fields:
      - label: "Innan"
        name: "innan"
        widget: "string"
        required: false
      - name: konserter
        label: Konserter
        label_singular: "Klassisk Konsert"
        widget: list
        summary: "{{fields.artist}}"
        fields:
          - label: "Text innan specifik konsert"
            name: "Text_before_specific_concert"
            widget: "string"
            required: false
          - label: "Artist"
            name: "artist"
            widget: "string"
            hint: "Namn på artist/grupp"
          - label: "Datum"
            name: "datum"
            widget: "datetime"
            format: "YYYY-MM-DD"
            dateFormat: "YYYY-MM-DD"
            timeFormat: false
            hint: "Datum för spelning"
      - label: "Efter"
        name: "efter"
        widget: "string"
        required: false

  - name: "meny"
    label: "Meny"
    folder: "content/meny/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{rubrik}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Rubrik"
        name: "rubrik"
        widget: "string"
      - label: "Innan"
        name: "innan"
        widget: "string"
        required: false
      - label: Dishes
        label_singular: "Dish"
        name: "dishes"
        widget: list
        summary: "{{fields.dish}}"
        fields:
          - label: Dish
            name: dish
            widget: "string"
          - label: "Dish description"
            name: dishDescription
            widget: "string"
            required: false
          - label: Price
            name: price
            widget: "string"
      - label: "Efter"
        name: "efter"
        widget: "string"
        required: false
