backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "konserter"
    label: "Konserter"
    folder: "content/konserter/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "konserter"
    fields:
      - label: "Innan"
        name: "innan"
        widget: "string"
        required: false
      - name: konserter
        label: Konserter
        label_singular: "Konsert"
        widget: list
        fields:
          - label: "Artist"
            name: "artist"
            widget: "string"
            hint: "Namn på artist/grupp"
          - label: "Datum"
            name: "datum"
            widget: "datetime"
            format: "YYYY-MM-DD"
            dateFormat: "YYYY-MM-DD"
            timeFormat: false
            hint: "Datum för spelning"
      - label: "Efter"
        name: "efter"
        widget: "string"
        required: false

  - name: "meny"
    label: "Meny"
    folder: "content/meny/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{rubrik}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Rubrik"
        name: "rubrik"
        widget: "string"
      - label: "Innan"
        name: "innan"
        widget: "string"
        required: false
      - label: Dishes
        label_singular: "Dish"
        name: "dishes"
        widget: list
        summary: "{{fields.dish}}"
        fields:
          - label: Dish
            name: dish
            widget: "string"
          - label: "Dish description"
            name: dishDescription
            widget: "string"
            required: false
          - label: Price
            name: price
            widget: "string"
      - label: "Efter"
        name: "efter"
        widget: "string"
        required: false
