backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "meny"
    label: "Meny"
    folder: "content/meny/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "meny"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "konserter"
    label: "Konserter"
    folder: "content/konserter/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "index"
    identifier_field: slug
    summary: "konserter"
    fields:
      - name: konserter
        label: Konserter
        label_singular: "Konsert"
        widget: list
        fields:
          - label: "Artist"
            name: "artist"
            widget: "string"
            hint: "Namn på artist/grupp"
          - label: "Datum"
            name: "datum"
            widget: "datetime"
            format: "YYYY-MM-DD"
            dateFormat: "YYYY-MM-DD"
            timeFormat: false
            hint: "Datum för spelning"

  - name: "menyx"
    label: "menyx"
    folder: "content/meny/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{rubrik}}"
    identifier_field: rubrik
    summary: "{{rubrik}}"
    fields:
      - name: "rubrik"
        label: "Rubrik"
        widget: "string"
        hint: "Meny rubrik"
      - name: konserter
        label: Konserter
        label_singular: "Konsert"
        widget: list
        fields:
          - label: "Maträtt"
            name: "maträtt"
            widget: "string"
            hint: "Namn på maträtt"
          - label: "Beskrivning"
            name: "beskrivning"
            widget: "string"
            hint: "Beskrivning av maträtt"
          - label: "Pris"
            name: "pris"
            widget: "string"
            hint: "Pris på maträtt"

  - name: "xx"
    label: "Xx"
    folder: "content/xx/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{rubrik}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Rubrik"
        name: "rubrik"
        widget: "string"
      - label: "Innan"
        name: "innan"
        widget: "string"
      - label: Dishes
        label_singular: "Dish"
        name: "dishes"
        widget: list
        summary: "{{fields.dish}}"
        fields:
          - label: Dish
            name: dish
            widget: "string"
          - label: "Dish description"
            name: dishDescription
            widget: "string"
            required: false
          - label: Price
            name: price
            widget: "string"
      - label: "Efter"
        name: "efter"
        widget: "string"

  # - name: "exp"
  #   label: "exp"
  #   folder: "content/meny/"
  #   extension: "mdx"
  #   format: "frontmatter"
  #   create: true
  #   slug: "{{slug}}"
  #   identifier_field: slug
  #   summary: "{{title}}"
  #   fields:
  #     - label: "Slug"
  #       name: "slug"
  #       widget: "string"
  #     - label: "Maträtt"
  #       name: "maträtt"
  #       widget: "string"
  #     - name: dishes
  #       label: Dishes
  #       label_singular: "Dish"
  #       widget: list
  #       fields:
  #         - label: "Maträtt"
  #           name: "maträtt"
  #           widget: "string"
  #           hint: "Namn på maträtt"
  #         - label: "Beskrivning"
  #           name: "beskrivning"
  #           widget: "string"
  #           hint: "Beskrivning av maträtt"
  #         - label: "Pris"
  #           name: "pris"
  #           widget: "string"
  #           hint: "Pris på maträtt"

  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "content/meny/index.mdx"
  #       label: "Meny"
  #       name: "meny"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "meny-page",
  #           }
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  # - file: "src/pages/lunchmeny/index.md"
  #   label: "Lunch Meny"
  #   name: "lunchmeny"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lunchmeny-page"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  # - file: "src/pages/konsert/index.md"
  #   label: "Konsert"
  #   name: "konsert"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lunchmeny-page"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  # - file: "content/meny/index.mdx"
  #   label: "Home"
  #   name: "home"
  #   fields:
  #     - { label: "Hero Title", name: "hero_title", widget: "string" }
  #     - {
  #         label: "Hero Description",
  #         name: "hero_description",
  #         widget: "markdown",
  #       }
